trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install gunicorn
  displayName: 'Installer les dépendances'

# Si vous n'avez pas besoin de pousser du code, vous pouvez commenter ou supprimer l'étape SSH suivante
# - task: InstallSSHKey@0
#   inputs:
#     sshPublicKey: '$(SSH_PUBLIC_KEY)'
#     sshKeySecureFile: 'id_rsa'
#     knownHostsEntry: '<github.com ou autre hôte SSH>'
#   displayName: 'Installer la clé SSH'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<nom-de-votre-service-connexion>'
    appType: 'webAppLinux'
    appName: '<nom-de-votre-app-azure>'
    package: '.'
    startupCommand: 'gunicorn --bind=0.0.0.0 --timeout 600 wsgi:app'
  displayName: 'Déployer sur Azure Web App'
